# Generated by Django 4.2 on 2023-08-07 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_website', models.CharField(blank=True, max_length=180, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=180, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=180, null=True)),
                ('country', models.CharField(blank=True, max_length=180, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='vendors/company/logos/')),
                ('vendor_license', models.ImageField(blank=True, null=True, upload_to='vendors/license/')),
                ('is_approved', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
                'db_table': 'vendors_vendor',
                'ordering': ('-created_at', 'user'),
            },
        ),
    ]
